const TELAS = {
  TELA_PRINCIPAL: 'TELA_PRINCIPAL',
  TELA_CONTADOR: 'TELA_CONTADOR',
  TELA_FORMULARIO: 'TELA_FORMULARIO',
  TELA_LISTA_TAREFAS: 'TELA_LISTA_TAREFAS',
  
  TELA_LOGIN: 'TELA_LOGIN'
};

export default TELAS;
