const TELAS = {
  TELA_PRINCIPAL: 'TELA_PRINCIPAL',
  TELA_CONTADOR: 'TELA_CONTADOR',
  TELA_FORMULARIO: 'TELA_FORMULARIO',
  TELA_LISTA_TAREFAS: 'TELA_LISTA_TAREFAS',
  TELA_LISTA_USUARIOS: 'TELA_LISTA_USUARIOS',
  TELA_DETALHES_USUARIOS: 'TELA_DETALHES_USUARIOS',

  TELA_PERFIL_USUARIO: 'TELA_PERFIL_USUARIO',
  TELA_LOGIN: 'TELA_LOGIN',
  TELA_NOVO_USUARIO: 'TELA_NOVO_USUARIO',
};

export default TELAS;
